<script lang="ts">
	import SectionComponent from '$lib/section/SectionComponent.svelte';
	import { mySections } from './SectionStore.js';
	$mySections = [
		{ title: 'Customization of the Typer', visible: false, ref: '#customization-of-the-typer-1' },
		{ title: 'Adding Typing Methods', visible: false, ref: '#adding-typing-methods-2' }
	];
	let visible: boolean[] = [];
	$: $mySections[0].visible = visible[0];
	$: $mySections[1].visible = visible[1];
	import copy from 'copy-to-clipboard';
	import { onMount } from 'svelte';

	/**
	 * This function will go through all the 'pre' elements
	 * on the page and add a copy button to them.
	 * Thanks to: https://slavbasharov.com/blog/adding-click-to-copy-code-markdown-blog
	 */
	onMount(() => {
		const codeBlocks = document.querySelectorAll('pre');
		codeBlocks.forEach((block) => {
			const copyPrompt = document.createElement('div');
			copyPrompt.className = 'copy-prompt';
			const copyPromptText = document.createElement('p');
			copyPromptText.innerHTML = '👆 Click to copy';
			copyPromptText.className = 'copy-prompt-p';
			const copyIcon = document.createElement('img');
			copyIcon.src = '/icons/copy-icon.svg';
			copyIcon.className = 'copy-prompt-img';
			copyPrompt.appendChild(copyIcon);
			copyPrompt.appendChild(copyPromptText);
			block.appendChild(copyPrompt);
			block.querySelector('.copy-prompt > p').addEventListener('click', (evt) => {
				copy(block.querySelector('code').textContent);
				block.querySelector('.copy-prompt > p').innerHTML = 'Copied!';
				setTimeout(() => {
					block.querySelector('.copy-prompt > p').innerHTML = '👆 Click to copy';
				}, 1000);
			});
		});
	});
	import PrevNextSection from '$lib/prevNext/PrevNextSection.svelte';

	let prevLink = '/Documentation/Customizations/Scoper_Customization';
	let nextLink = '/Documentation/Customizations/Validator_Customization';
</script>

<PrevNextSection {prevLink} {nextLink} />
<SectionComponent tag="h1" id="customization-of-the-typer-1" bind:intersecting={visible[0]}>Customization of the Typer</SectionComponent>
<p>
	The typer can be customized <strong>per concept</strong>. Your new typer needs to implement the
	<a href="/Documentation/Under_the_Hood/FreTool_Interfaces#fretyper-5">FreTyper interface</a>.
</p>
<p>
	As a convenience, Freon generates a file <code>~/freon/typer/CustomYourLanguageNameTyperPart.ts</code>, which will not be overwritten upon
	regeneration. It already contains a class that implements this interface.
</p>
<SectionComponent tag="h2" id="adding-typing-methods-2" bind:intersecting={visible[1]}>Adding Typing Methods</SectionComponent>
<p>
	In the new typer class add the code you want to add in one or more of the methods. Let the method return ‘null’ to let Freon know that the
	typer from the Freon Definition Level should be used instead.
</p>
<p>
	The following code changes the <code>conformsList</code> method for lists of <code>Variables</code>. It checks the lists in reverse order:
	A-B-C conforms to C-B-A.
</p>
<pre
	class="language-ts">{@html `<code class="language-ts"><span class="token comment">// CustomizationsProject/src/custom/typer/CustomEntityModelTyperPart.ts</span>

<span class="token comment">// Generated by the Freon Language Generator.</span>
<span class="token keyword">import</span> <span class="token punctuation">&#123;</span> FreNode<span class="token punctuation">,</span> FreType<span class="token punctuation">,</span> FreTyper <span class="token punctuation">&#125;</span> <span class="token keyword">from</span> <span class="token string">"@freon4dsl/core"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">&#123;</span>Variable<span class="token punctuation">&#125;</span> <span class="token keyword">from</span> <span class="token string">"../language/gen/index.js"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">&#123;</span>EntityModelEnvironment<span class="token punctuation">&#125;</span> <span class="token keyword">from</span> <span class="token string">"../config/gen/EntityModelEnvironment.js"</span><span class="token punctuation">;</span>

<span class="token comment">/**
 * Class 'CustomEntityModelTyperPart' is meant to be a convient place to add any
 * custom code for type checking.
 */</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">CustomEntityModelTyperPart</span> <span class="token keyword">implements</span> <span class="token class-name">FreTyper</span> <span class="token punctuation">&#123;</span>
    mainTyper<span class="token operator">:</span> FreTyper<span class="token punctuation">;</span>

    <span class="token function">isType</span><span class="token punctuation">(</span>modelelement<span class="token operator">:</span> FreNode<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token function">inferType</span><span class="token punctuation">(</span>modelelement<span class="token operator">:</span> FreNode<span class="token punctuation">)</span><span class="token operator">:</span> FreType <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token function">equals</span><span class="token punctuation">(</span>type1<span class="token operator">:</span> FreType<span class="token punctuation">,</span> type2<span class="token operator">:</span> FreType<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token function">conforms</span><span class="token punctuation">(</span>type1<span class="token operator">:</span> FreType<span class="token punctuation">,</span> type2<span class="token operator">:</span> FreType<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token comment">/**
     * Example of custom typings: typelist2 conforms to typelist1 if the elements
     * conform in the opposite direction, i.e. [A, B, C] conforms to [C, B, A]
     * @param typelist1
     * @param typelist2
     */</span>
    <span class="token function">conformsList</span><span class="token punctuation">(</span>typelist1<span class="token operator">:</span> FreType<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> typelist2<span class="token operator">:</span> FreType<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>typelist1<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>typelist1<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token keyword">instanceof</span> <span class="token class-name">Variable</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>typelist1<span class="token punctuation">.</span>length <span class="token operator">!==</span> typelist2<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
            <span class="token keyword">let</span> result<span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
            <span class="token keyword">const</span> max_length <span class="token operator">=</span> typelist1<span class="token punctuation">.</span>length<span class="token punctuation">;</span>
            <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> typelist1<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
                result <span class="token operator">=</span> EntityModelEnvironment<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>typer<span class="token punctuation">.</span><span class="token function">conforms</span><span class="token punctuation">(</span>typelist1<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">,</span> typelist2<span class="token punctuation">[</span>max_length <span class="token operator">-</span> i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>result <span class="token operator">==</span> <span class="token boolean">false</span><span class="token punctuation">)</span> <span class="token keyword">return</span> result<span class="token punctuation">;</span>
            <span class="token punctuation">&#125;</span>
            <span class="token keyword">return</span> result<span class="token punctuation">;</span>
        <span class="token punctuation">&#125;</span> <span class="token keyword">else</span> <span class="token punctuation">&#123;</span>
            <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
        <span class="token punctuation">&#125;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token function">commonSuper</span><span class="token punctuation">(</span>typelist<span class="token operator">:</span> FreType<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> FreType <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token keyword">public</span> <span class="token function">getSuperTypes</span><span class="token punctuation">(</span>type<span class="token operator">:</span> FreType<span class="token punctuation">)</span><span class="token operator">:</span> FreType<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>
<span class="token punctuation">&#125;</span>
</code>`}</pre>

<PrevNextSection {prevLink} {nextLink} />
