<script lang="ts">
	import SectionComponent from '$lib/section/SectionComponent.svelte';
	import { mySections } from './SectionStore.js';
	$mySections = [{ title: 'Under the Hood', visible: false, ref: '#under-the-hood-1' }];
	let visible: boolean[] = [];
	$: $mySections[0].visible = visible[0];
	import copy from 'copy-to-clipboard';
	import { onMount } from 'svelte';

	/**
	 * This function will go through all the 'pre' elements
	 * on the page and add a copy button to them.
	 * Thanks to: https://slavbasharov.com/blog/adding-click-to-copy-code-markdown-blog
	 */
	onMount(() => {
		const codeBlocks = document.querySelectorAll('pre');
		codeBlocks.forEach((block) => {
			const copyPrompt = document.createElement('div');
			copyPrompt.className = 'copy-prompt';
			const copyPromptText = document.createElement('p');
			copyPromptText.innerHTML = '👆 Click to copy';
			copyPromptText.className = 'copy-prompt-p';
			const copyIcon = document.createElement('img');
			copyIcon.src = '/icons/copy-icon.svg';
			copyIcon.className = 'copy-prompt-img';
			copyPrompt.appendChild(copyIcon);
			copyPrompt.appendChild(copyPromptText);
			block.appendChild(copyPrompt);
			block.querySelector('.copy-prompt > p').addEventListener('click', (evt) => {
				copy(block.querySelector('code').textContent);
				block.querySelector('.copy-prompt > p').innerHTML = 'Copied!';
				setTimeout(() => {
					block.querySelector('.copy-prompt > p').innerHTML = '👆 Click to copy';
				}, 1000);
			});
		});
	});
	import PrevNextSection from '$lib/prevNext/PrevNextSection.svelte';

	let prevLink = '/Documentation/CommandLine';
	let nextLink = '/Documentation/Under_the_Hood/Editor_Framework';
</script>

<PrevNextSection {prevLink} {nextLink} />
<SectionComponent tag="h1" id="under-the-hood-1" bind:intersecting={visible[0]}>Under the Hood</SectionComponent>
<p>
	Before you dive deeper under the hood of this project, we invite you to read about the
	<a href="/Background">Background</a> used during the creation of this tool.
</p>
<p>This section can be roughly divided into three parts.</p>
<ol>
	<li>
		Information about the core <a href="/Documentation/Under_the_Hood/Editor_Framework">framework</a> of Freon, the classes that are used to
		build the editors.
	</li>
	<li>
		Information on the <a href="/Documentation/Under_the_Hood/FreTool_Interfaces">interfaces of all fre-tools</a>, e.g. the scoper, the
		validator, used and generated by Freon.
	</li>
	<li>
		Information on the (open) source code of Freon can be found on <a href="https://github.com/freon4dsl/Freon4dsl" target="_blank"
			>https://github.com/freon4dsl/Freon4dsl</a
		>.
	</li>
</ol>

<PrevNextSection {prevLink} {nextLink} />
