<script lang="ts">
	import SectionComponent from '$lib/section/SectionComponent.svelte';
	import { mySections } from './SectionStore.js';
	$mySections = [
		{ title: 'Making an Editor for your DSL', visible: false, ref: '#making-an-editor-for-your-dsl-1' },
		{ title: 'The default editor', visible: false, ref: '#the-default-editor-2' },
		{ title: 'A projection for the Topic model unit', visible: false, ref: '#a-projection-for-the-topic-model-unit-3' },
		{ title: 'The Possibilities for Lists', visible: false, ref: '#the-possibilities-for-lists-4' },
		{ title: 'Inherited Projections', visible: false, ref: '#inherited-projections-5' },
		{ title: 'Triggers', visible: false, ref: '#triggers-6' }
	];
	let visible: boolean[] = [];
	$: $mySections[0].visible = visible[0];
	$: $mySections[1].visible = visible[1];
	$: $mySections[2].visible = visible[2];
	$: $mySections[3].visible = visible[3];
	$: $mySections[4].visible = visible[4];
	$: $mySections[5].visible = visible[5];
	import copy from 'copy-to-clipboard';
	import { onMount } from 'svelte';

	/**
	 * This function will go through all the 'pre' elements
	 * on the page and add a copy button to them.
	 * Thanks to: https://slavbasharov.com/blog/adding-click-to-copy-code-markdown-blog
	 */
	onMount(() => {
		const codeBlocks = document.querySelectorAll('pre');
		codeBlocks.forEach((block) => {
			const copyPrompt = document.createElement('div');
			copyPrompt.className = 'copy-prompt';
			const copyPromptText = document.createElement('p');
			copyPromptText.innerHTML = '👆 Click to copy';
			copyPromptText.className = 'copy-prompt-p';
			const copyIcon = document.createElement('img');
			copyIcon.src = '/icons/copy-icon.svg';
			copyIcon.className = 'copy-prompt-img';
			copyPrompt.appendChild(copyIcon);
			copyPrompt.appendChild(copyPromptText);
			block.appendChild(copyPrompt);
			block.querySelector('.copy-prompt > p').addEventListener('click', (evt) => {
				copy(block.querySelector('code').textContent);
				block.querySelector('.copy-prompt > p').innerHTML = 'Copied!';
				setTimeout(() => {
					block.querySelector('.copy-prompt > p').innerHTML = '👆 Click to copy';
				}, 1000);
			});
		});
	});
	import PrevNextSection from '$lib/prevNext/PrevNextSection.svelte';

	let prevLink = '/Tutorial/Creating_your_Metamodel';
	let nextLink = '/Tutorial/More_Fun_with_Projections';

	import Figure from '$lib/figures/Figure.svelte';
</script>

<PrevNextSection {prevLink} {nextLink} />

<SectionComponent tag="h1" id="making-an-editor-for-your-dsl-1" bind:intersecting={visible[0]}
	>Making an Editor for your DSL</SectionComponent
>
<p>At last, your patience is rewarded. In this step of the tutorial we are going to make the editor looking great!</p>
<SectionComponent tag="h2" id="the-default-editor-2" bind:intersecting={visible[1]}>The default editor</SectionComponent>
<p>
	Let’s create a file called <code>edu-main.edit</code> in the <code>src/defs</code> folder, and define a default editor for this model unit.
	Please, enter the following line.
</p>
<pre class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L3-L3
</span>
<span class="token keyword">editor</span> <span class="token keyword">default</span></code>`}</pre>
<p>There, that’s done!</p>
<p>
	No, of course we are not done. Just kidding, and showing you that Freon will add a default <a
		href="/Documentation/Defining_an_Editor/Projections">projection</a
	> for any concept that is not included in the editor definition. You can build your editor concept by concept.
</p>
<p>In fact, the editor that is generated in lesson 1, is completely based on the defaults generated by Freon.</p>
<Figure imageName={'tutorial/Tutorial-lesson2-screenshot1.png'} caption={'Editor from lesson 1'} figureNumber={2} />
<SectionComponent tag="h2" id="a-projection-for-the-topic-model-unit-3" bind:intersecting={visible[2]}
	>A projection for the <em>Topic</em> model unit</SectionComponent
>
<p>
	A complete editor definition is build from a number of projections. To define a single projection we need the name of the concept, some
	curly brackets, and, last but not least a pair of square brackets. Everything that goes between the square brackets will be taken as
	literal as possible into the editor, that is, if there is indentation or literal text, this will be projected as unchangeable strings.
</p>
<p>
	The first step is to focus on the <em>Topic</em> model unit. Let’s state how this model unit should look. The projection for
	<em>Topic</em> consists of four parts.
</p>
<ul>
	<li>
		A line with the fixed string <code>SiteGroup:</code> followed by the name of the site group. For the latter we use a syntax similar to
		the smart strings in TypeScript: <code>$&#123;self.main&#125;</code>. You may leave out the <code>self.</code> part. It indicates that
		we refer to the property of the <em>Topic</em> object that is projected. For clarity, we will be using this prefix everywhere in the tutorial.
	</li>
	<li>A line with the fixed string <code>Topic:</code> followed by the name of the unit.</li>
	<li>
		The third line is again similar, but projects the <code>description</code> property of the model unit. Next, we add an empty line which,
		like the indentation, will show in the editor.
	</li>
	<li>
		The last part of the definition gives the projection of the <code>pages</code> property, which is a list. By adding the keyword
		<code>vertical</code>
		we tell Freon to project the list vertically.
	</li>
</ul>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L3-L16
</span>
<span class="token keyword">editor</span> <span class="token keyword">default</span>

<span class="token class-name">Topic</span> &#123;<span class="token punctuation">[</span>
    SiteGroup: $&#123;<span class="token function"><span class="token variable">self</span>.main</span>&#125;
    Topic: $&#123;<span class="token function"><span class="token variable">self</span>.name</span>&#125;
    Topic description: $&#123;<span class="token function"><span class="token variable">self</span>.description</span>&#125;

    Pages:
    $&#123;<span class="token function"><span class="token variable">self</span>.pages <span class="token keyword">vertical</span> </span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">Page</span> &#123;<span class="token punctuation">[</span>
    $&#123;<span class="token function"><span class="token variable">self</span>.name</span>&#125;
<span class="token punctuation">]</span>&#125;</code>`}</pre>
<SectionComponent tag="h2" id="the-possibilities-for-lists-4" bind:intersecting={visible[3]}>The Possibilities for Lists</SectionComponent>
<p>
	Above we have projected the pages as a vertical list. There are many options to project lists. First, not all lists need to be projected
	vertically. Use the keyword <code>horizontal</code> to display all list elements on a single line. The keyword may also be omitted, the
	default value is <code>vertical</code>.
</p>
<p>
	In the next projection, for the <em>Theory</em> concept we project two lists: <code>self.content</code> and <code>self.questions</code>.
	Notice that we added something to the projection of <code>self.content</code> in the above definition:
	<code>terminator[== END OF LINE]</code>. It means that after every element of the list the string ’== END OF LINE’ character is projected.
	Note that the line of dashes will also appear in the editor.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token class-name">Theory</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    Theory
        $&#123;<span class="token function"><span class="token variable">self</span>.content <span class="token keyword">vertical</span> <span class="token keyword">terminator</span>[== END OF LINE]</span>&#125;

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;
</code>`}</pre>
<p>
	Instead of using a terminator, you could also opt for a <code>separator</code>, where the character or string is projected between every
	element of the list, or an <code>initiator</code>, which projects the character or string before the element.
</p>
<p>Here are some examples of how you can tweak the display.</p>
<pre class="language-freon">{@html `<code class="language-freon">    Theory
        $&#123;<span class="token function"><span class="token variable">self</span>.contents <span class="token keyword">vertical</span> <span class="token keyword">separator</span> [.]</span>&#125;

    Theory
        $&#123;<span class="token function"><span class="token variable">self</span>.content <span class="token keyword">horizontal</span> <span class="token keyword">terminator</span> [====]</span>&#125;

    Theory
        $&#123;<span class="token function"><span class="token variable">self</span>.content <span class="token keyword">vertical</span> initiator [Line]</span>&#125;</code>`}</pre>
<p>Go ahead and try the different options.</p>
<SectionComponent tag="h2" id="inherited-projections-5" bind:intersecting={visible[4]}>Inherited Projections</SectionComponent>
<p>
	Remember that we defined the concept <code>Page</code> to be abstract, and there were a lot of concepts that inherit from
	<code>Page</code>? Of course, we can build inherited projection definitions as well. We have defined the projection for the abstract
	concept <code>Page</code> as follows. It’s nothing fancy, but you could do more, if you like.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L14-L16
</span>
<span class="token class-name">Page</span> &#123;<span class="token punctuation">[</span>
    $&#123;<span class="token function"><span class="token variable">self</span>.name</span>&#125;
<span class="token punctuation">]</span>&#125;</code>`}</pre>
<p>
	Now look at how we incorporate this projection in the projection of one of <code>Page</code>’s children using this syntax:
	<code>[=&gt;Page]</code>. It means that we will include the default projection of <em>Page</em> right there. Note that we can use
	inherited properties, like <code>questions</code>, as expected in the projection.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L18-L25
</span>
<span class="token class-name">Theory</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    Theory <span class="token punctuation">[</span>=>Page<span class="token punctuation">]</span>
        $&#123;<span class="token function"><span class="token variable">self</span>.content <span class="token keyword">vertical</span> <span class="token keyword">terminator</span>[== END OF LINE]</span>&#125;

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;</code>`}</pre>
<p>
	Now we can almost finish the projection for this model unit by adding the following lines. Each concept that inherits from <code
		>Page</code
	>
	is defined, as well as the <code>questions</code> and <code>content</code> parts of <code>Page</code>.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L27-L76
</span>
<span class="token class-name">Video</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    Video <span class="token punctuation">[</span>=>Page<span class="token punctuation">]</span>
        Maybe this video will help you understand.
        $&#123;<span class="token function"><span class="token variable">self</span>.url</span>&#125;

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">WorkSheet</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    Worksheet <span class="token punctuation">[</span>=>Page<span class="token punctuation">]</span>
        See if you can answer the following questions.

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">ExamplePage</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    Example <span class="token punctuation">[</span>=>Page<span class="token punctuation">]</span>
        $&#123;<span class="token function"><span class="token variable">self</span>.content</span>&#125;

        Now, please, answer the following questions.

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">InDepthMaterial</span> &#123;<span class="token punctuation">[</span>
    ----------------------------------------------------
    InDepthMaterial <span class="token punctuation">[</span>=>Page<span class="token punctuation">]</span>
        $&#123;<span class="token function"><span class="token variable">self</span>.content</span>&#125;

        Test your understanding by answering the following questions.

    Questions:
        $&#123;<span class="token function"><span class="token variable">self</span>.questions <span class="token keyword">vertical</span></span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">Question</span> &#123;<span class="token punctuation">[</span>
    $&#123;<span class="token function"><span class="token variable">self</span>.name</span>&#125;
        $&#123;<span class="token function"><span class="token variable">self</span>.content</span>&#125;
        Correct Answer: $&#123;<span class="token function"><span class="token variable">self</span>.correctAnswer</span>&#125;
<span class="token punctuation">]</span>&#125;

<span class="token class-name">Line</span> &#123;
    <span class="token punctuation">[</span>$&#123;<span class="token function"><span class="token variable">self</span>.content</span>&#125;<span class="token punctuation">]</span>
&#125;</code>`}</pre>
<SectionComponent tag="h2" id="triggers-6" bind:intersecting={visible[5]}>Triggers</SectionComponent>
<p>
	Last thing to learn in this lesson is how we can make editing easier for the user. Remember that we needed a concept for numeric
	fractions? Its called <code>Fraction</code>, and it is formed by combining two numbers, a numerator and a denominator. This is how the
	concept is defined in the .ast file.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.ast#L53-L56
</span>
<span class="token keyword">concept</span> <span class="token class-name">Fraction</span> <span class="token keyword">base</span> <span class="token class-name">NumberConcept</span> &#123;
    numerator: <span class="token builtin">number</span>;
    denominator: <span class="token builtin">number</span>;
&#125;</code>`}</pre>
<p>
	In Freon the user must first choose the Fraction option from a dropdown menu before he/she can enter any number. To avoid this extra step
	in editing, we can tell Freon that when a certain key or string is entered, it should automatically create an instance of the associated
	concept. The key or string to be entered is called the <strong>trigger</strong>.
</p>
<p>
	For the Fraction concept we defined the trigger to be a forwards slash. If the user wants to add a correct answer to a question, where the
	possibilities are either a <em>SimpleNumber</em> or a <em>Fraction</em>, entering the ’/’ will produce a <em>Fraction</em> instance. So, the
	last two projections are defined as follows.
</p>
<pre
	class="language-freon">{@html `<code class="language-freon"><span class="token comment">// Education/lesson2-defs/edu-topics.edit#L78-L85
</span>
<span class="token class-name">SimpleNumber</span> &#123;
    <span class="token punctuation">[</span>$&#123;<span class="token function"><span class="token variable">self</span>.value</span>&#125;<span class="token punctuation">]</span>
&#125;

<span class="token class-name">Fraction</span> &#123;
    <span class="token punctuation">[</span>$&#123;<span class="token function">numerator</span>&#125; / $&#123;<span class="token function">denominator</span>&#125;<span class="token punctuation">]</span>
    <span class="token keyword">trigger</span> = <span class="token string">"/"</span>
&#125;</code>`}</pre>
<p>
	Now go ahead, generate a new editor, and have a look. Your editor should now look like this. Much better than the result from lesson 1!
</p>
<Figure
	imageName={'tutorial/Tutorial-lesson2-screenshot2.png'}
	caption={'Editor after adding some projection definitions'}
	figureNumber={3}
/>
<p>
	When you’ve gotten this far, it might be a good idea to try for yourself what happens if you change the projection, for instance, you
	might switch the order of the lines. But don’t forget to get back to the next part of the tutorial, where we will have more fun with
	defining projections.
</p>

<PrevNextSection {prevLink} {nextLink} />
