// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { XXDefaultWorker } from "../utils/gen/XXDefaultWorker.js";
import { XXCheckerInterface } from "./gen/XXValidator.js";

export class CustomXXValidator extends XXDefaultWorker implements XXCheckerInterface {
    errorList: FreError[] = [];
}
