// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomXXActions, CustomXXProjection } from "../editor/index.js";
import { CustomXXScoper } from "../scoper/index.js";
import { CustomXXTyperPart } from "../typer/CustomXXTyperPart.js";
import { CustomXXValidator } from "../validator/index.js";
import { CustomXXStdlib } from "../stdlib/CustomXXStdlib.js";
import { XXCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomXXProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomXXActions()];
    // add your custom validations here
    customValidations: XXCheckerInterface[] = [new CustomXXValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomXXScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomXXTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomXXStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
