// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { EducationDefaultWorker } from "../utils/gen/EducationDefaultWorker.js";
import { EducationCheckerInterface } from "./gen/EducationValidator.js";

export class CustomEducationValidator extends EducationDefaultWorker implements EducationCheckerInterface {
    errorList: FreError[] = [];
}
